<a href="https://colab.research.google.com/github/VarelAntoni/machine_learning_project/blob/main/movies_dataset/movies_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [229]:
#Import libraries
import numpy as np
import pandas as pd
import math
import random
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [230]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/tmdb/tmdb-movie-metadata/versions/2

In [231]:
print(os.listdir(path))

['tmdb_5000_movies.csv', 'tmdb_5000_credits.csv']

In [232]:
df = pd.read_csv(os.path.join(path, 'tmdb_5000_movies.csv'))

In [233]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [234]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [235]:
df = df[['id', 'title', 'genres', 'budget', 'popularity', 'release_date', 'revenue', 'vote_average']]

In [236]:
df.head()

,id,title,genres,budget,popularity,release_date,revenue,vote_average
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",237000000,150.437577,2009-12-10,2787965087,7.2
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",300000000,139.082615,2007-05-19,961000000,6.9
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",245000000,107.376788,2015-10-26,880674609,6.3
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",250000000,112.312950,2012-07-16,1084939099,7.6
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",260000000,43.926995,2012-03-07,284139100,6.1

In [237]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4803 non-null   int64
 1   title         4803 non-null   object
 2   genres        4803 non-null   object
 3   budget        4803 non-null   int64
 4   popularity    4803 non-null   float64
 5   release_date  4802 non-null   object
 6   revenue       4803 non-null   int64
 7   vote_average  4803 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 300.3+ KB

In [238]:
df.columns

Index(['id', 'title', 'genres', 'budget', 'popularity', 'release_date',
       'revenue', 'vote_average'],
      dtype='object')

In [239]:
# Check if any rows have 'id' equal to 1
if df[df['id'] == 28].empty:
    print("No rows found with id equal to 1.")
else:
    # If rows with 'id' equal to 1 exist, access the 'genres' column
    print(df.loc[df['id'] == 28, 'genres'].iloc[0])

[{"id": 18, "name": "Drama"}, {"id": 10752, "name": "War"}]

In [240]:
print(df['genres'].iloc[1])

[{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]

In [241]:
import json

df['genres'] = df['genres'].apply(json.loads)

In [242]:
df['genre_names'] = df['genres'].apply(lambda x: [d['name'] for d in x])

df_exploded = df.explode('genre_names', ignore_index=True)

In [243]:
df_exploded.head()

,id,title,genres,budget,popularity,release_date,revenue,vote_average,genre_names
0,19995,Avatar,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",237000000,150.437577,2009-12-10,2787965087,7.2,Action
1,19995,Avatar,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",237000000,150.437577,2009-12-10,2787965087,7.2,Adventure
2,19995,Avatar,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",237000000,150.437577,2009-12-10,2787965087,7.2,Fantasy
3,19995,Avatar,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",237000000,150.437577,2009-12-10,2787965087,7.2,Science Fiction
4,285,Pirates of the Caribbean: At World's End,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",300000000,139.082615,2007-05-19,961000000,6.9,Adventure

In [244]:
df = df_exploded.drop('genres', axis=1)

In [245]:
df['gross'] = df['revenue'] - df['budget']

In [246]:
df.head(10)

,id,title,budget,popularity,release_date,revenue,vote_average,genre_names,gross
0,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Action,2550965087
1,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Adventure,2550965087
2,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Fantasy,2550965087
3,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Science Fiction,2550965087
4,285,Pirates of the Caribbean: At World's End,300000000,139.082615,2007-05-19,961000000,6.9,Adventure,661000000
5,285,Pirates of the Caribbean: At World's End,300000000,139.082615,2007-05-19,961000000,6.9,Fantasy,661000000
6,285,Pirates of the Caribbean: At World's End,300000000,139.082615,2007-05-19,961000000,6.9,Action,661000000
7,206647,Spectre,245000000,107.376788,2015-10-26,880674609,6.3,Action,635674609
8,206647,Spectre,245000000,107.376788,2015-10-26,880674609,6.3,Adventure,635674609
9,206647,Spectre,245000000,107.376788,2015-10-26,880674609,6.3,Crime,635674609

In [247]:
# Normalisasi kolom popularity ke skala 1-10
min_pop = df['popularity'].min()
max_pop = df['popularity'].max()

df['popularity_scaled'] = (1 + ((df['popularity'] - min_pop) / (max_pop - min_pop)) * (100 - 1)).round(1)

In [248]:
df['release_date'] = pd.to_datetime(df['release_date'])
df['title_year'] = df['release_date'].dt.year

In [249]:
df.head()

,id,title,budget,popularity,release_date,revenue,vote_average,genre_names,gross,popularity_scaled,title_year
0,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Action,2550965087,18.0,2009.0
1,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Adventure,2550965087,18.0,2009.0
2,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Fantasy,2550965087,18.0,2009.0
3,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Science Fiction,2550965087,18.0,2009.0
4,285,Pirates of the Caribbean: At World's End,300000000,139.082615,2007-05-19,961000000,6.9,Adventure,661000000,16.7,2007.0

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12188 entries, 0 to 12187
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 12188 non-null  int64
 1   title              12188 non-null  object
 2   budget             12188 non-null  int64
 3   popularity         12188 non-null  float64
 4   release_date       12187 non-null  datetime64[ns]
 5   revenue            12188 non-null  int64
 6   vote_average       12188 non-null  float64
 7   genre_names        12160 non-null  object
 8   gross              12188 non-null  int64
 9   popularity_scaled  12188 non-null  float64
 10  title_year         12187 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(2)
memory usage: 1.0+ MB

In [251]:
movie_metadata = pd.read_csv("movie_metadata.csv")
movie_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [252]:
movie_metadata = movie_metadata[['title_year', 'imdb_score']]

In [253]:
# Merge on a common column (e.g., 'id')
merged_df = pd.merge(df, movie_metadata, on='title_year')  # Default is an inner join

# Save the merged data to a new CSV
merged_df.to_csv('merged_movie_data.csv', index=False)

print("Merged data saved to 'merged_movie_data.csv'")

Merged data saved to 'merged_movie_data.csv'

In [254]:
df = pd.read_csv('merged_movie_data.csv')

In [255]:
df.head()

,id,title,budget,popularity,release_date,revenue,vote_average,genre_names,gross,popularity_scaled,title_year,imdb_score
0,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Action,2550965087,18.0,2009.0,7.9
1,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Action,2550965087,18.0,2009.0,7.5
2,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Action,2550965087,18.0,2009.0,6.0
3,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Action,2550965087,18.0,2009.0,6.6
4,19995,Avatar,237000000,150.437577,2009-12-10,2787965087,7.2,Action,2550965087,18.0,2009.0,5.8

In [256]:
df = df[['title_year', 'gross', 'popularity_scaled', 'imdb_score', 'vote_average', 'genre_names']]

In [257]:
df = df.rename(columns={'title_year': 'year'})
df = df.rename(columns={'genre_names': 'genre'})
df = df.rename(columns={'popularity_scaled': 'popularity'})

In [258]:
df.tail()

           year  gross  popularity  imdb_score  vote_average        genre
2140551  2005.0      0         1.2         7.3           6.3  Documentary
2140552  2005.0      0         1.2         6.9           6.3  Documentary
2140553  2005.0      0         1.2         6.6           6.3  Documentary
2140554  2005.0      0         1.2         6.3           6.3  Documentary
2140555  2005.0      0         1.2         7.8           6.3  Documentary

In [259]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2140556 entries, 0 to 2140555
Data columns (total 6 columns):
 #   Column        Dtype
---  ------        -----
 0   year          float64
 1   gross         int64
 2   popularity    float64
 3   imdb_score    float64
 4   vote_average  float64
 5   genre         object
dtypes: float64(4), int64(1), object(1)
memory usage: 98.0+ MB

In [260]:
df.isnull().sum()

year             108
gross              0
popularity         0
imdb_score         0
vote_average       0
genre           5784
dtype: int64

In [261]:
df.dropna(inplace=True)

In [262]:
df['year'] = df['year'].astype(int)

In [263]:
# Simpan data yang sudah ada label
df.to_csv('movies_dataset_summary.csv')